"""add out_of_book columns and deepest_opening

Revision ID: 97956c62ce73
Revises: 672e3ae5a9fc
Create Date: 2026-06-17 16:07:25.264118
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '97956c62ce73'
down_revision: Union[str, None] = '672e3ae5a9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('my_out_of_book_ply', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('opp_out_of_book_ply', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('deepest_opening_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'openings', ['deepest_opening_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'deepest_opening_id')
    op.drop_column('games', 'opp_out_of_book_ply')
    op.drop_column('games', 'my_out_of_book_ply')
    # ### end Alembic commands ###
