"""deep analysis fields

Revision ID: e3b87853c4e2
Revises: a0500fdf2950
Create Date: 2026-06-17 19:48:19.411259
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e3b87853c4e2'
down_revision: Union[str, None] = 'a0500fdf2950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('move_analyses', sa.Column('deep_depth', sa.Integer(), nullable=True))
    op.add_column('move_analyses', sa.Column('deep_eval_cp', sa.Integer(), nullable=True))
    op.add_column('move_analyses', sa.Column('deep_eval_mate', sa.Integer(), nullable=True))
    op.add_column('move_analyses', sa.Column('deep_best_uci', sa.String(length=8), nullable=True))
    op.add_column('move_analyses', sa.Column('deep_best_san', sa.String(length=10), nullable=True))
    op.add_column('move_analyses', sa.Column('deep_pv', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('move_analyses', 'deep_pv')
    op.drop_column('move_analyses', 'deep_best_san')
    op.drop_column('move_analyses', 'deep_best_uci')
    op.drop_column('move_analyses', 'deep_eval_mate')
    op.drop_column('move_analyses', 'deep_eval_cp')
    op.drop_column('move_analyses', 'deep_depth')
    # ### end Alembic commands ###
