"""daily plan tables

Revision ID: caab7def4c9e
Revises: cabca61f3d33
Create Date: 2026-06-17 19:06:58.829467
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'caab7def4c9e'
down_revision: Union[str, None] = 'cabca61f3d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('target_minutes', sa.Integer(), nullable=False),
    sa.Column('coach_message', sa.Text(), nullable=True),
    sa.Column('weakness_focus', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'plan_date', name='uq_daily_plan_player_date')
    )
    op.create_index('ix_daily_plans_plan_date', 'daily_plans', ['plan_date'], unique=False)
    op.create_index(op.f('ix_daily_plans_player_id'), 'daily_plans', ['player_id'], unique=False)
    op.create_table('daily_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['daily_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_plan_items_kind'), 'daily_plan_items', ['kind'], unique=False)
    op.create_index(op.f('ix_daily_plan_items_plan_id'), 'daily_plan_items', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_plan_items_plan_id'), table_name='daily_plan_items')
    op.drop_index(op.f('ix_daily_plan_items_kind'), table_name='daily_plan_items')
    op.drop_table('daily_plan_items')
    op.drop_index(op.f('ix_daily_plans_player_id'), table_name='daily_plans')
    op.drop_index('ix_daily_plans_plan_date', table_name='daily_plans')
    op.drop_table('daily_plans')
    # ### end Alembic commands ###
