"""weekly reports

Revision ID: d03a678319ad
Revises: 1ead05e26358
Create Date: 2026-06-18 10:15:42.268414
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd03a678319ad'
down_revision: Union[str, None] = '1ead05e26358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('elo_delta', sa.Integer(), nullable=False),
    sa.Column('puzzles_solved', sa.Integer(), nullable=False),
    sa.Column('rep_cards_reviewed', sa.Integer(), nullable=False),
    sa.Column('plans_completed', sa.Integer(), nullable=False),
    sa.Column('blunders_this_week', sa.Integer(), nullable=False),
    sa.Column('weakness_deltas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_focus_for_next_week', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'week_start', name='uq_weekly_report_player_week')
    )
    op.create_index(op.f('ix_weekly_reports_player_id'), 'weekly_reports', ['player_id'], unique=False)
    op.create_index('ix_weekly_reports_week_start', 'weekly_reports', ['week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weekly_reports_week_start', table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_player_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    # ### end Alembic commands ###
