"""metric snapshot

Revision ID: a0500fdf2950
Revises: db6787112a13
Create Date: 2026-06-17 19:37:35.512170
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a0500fdf2950'
down_revision: Union[str, None] = 'db6787112a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating_rapid', sa.Integer(), nullable=True),
    sa.Column('rating_blitz', sa.Integer(), nullable=True),
    sa.Column('rating_bullet', sa.Integer(), nullable=True),
    sa.Column('games_total', sa.Integer(), nullable=False),
    sa.Column('games_30d', sa.Integer(), nullable=False),
    sa.Column('games_7d', sa.Integer(), nullable=False),
    sa.Column('winrate_white', sa.Float(), nullable=True),
    sa.Column('winrate_black', sa.Float(), nullable=True),
    sa.Column('exercises_solved_total', sa.Integer(), nullable=False),
    sa.Column('exercises_solved_7d', sa.Integer(), nullable=False),
    sa.Column('rep_cards_reviewed_7d', sa.Integer(), nullable=False),
    sa.Column('plans_completed_7d', sa.Integer(), nullable=False),
    sa.Column('weakness_severities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('puzzles_solved_by_theme', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repertoire_due', sa.Integer(), nullable=True),
    sa.Column('exercises_due', sa.Integer(), nullable=True),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshots_player_id'), 'metric_snapshots', ['player_id'], unique=False)
    op.create_index('ix_metric_snapshots_player_taken', 'metric_snapshots', ['player_id', 'taken_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metric_snapshots_player_taken', table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_player_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    # ### end Alembic commands ###
