"""gm annotations on repertoire

Revision ID: 1ead05e26358
Revises: e3b87853c4e2
Create Date: 2026-06-18 08:51:31.863870
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1ead05e26358'
down_revision: Union[str, None] = 'e3b87853c4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repertoire_nodes', sa.Column('gm_total_games', sa.Integer(), nullable=True))
    op.add_column('repertoire_nodes', sa.Column('gm_moves', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('repertoire_nodes', sa.Column('gm_my_move_score', sa.Float(), nullable=True))
    op.add_column('repertoire_nodes', sa.Column('gm_my_move_share', sa.Float(), nullable=True))
    op.add_column('repertoire_nodes', sa.Column('gm_annotated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repertoire_nodes', 'gm_annotated_at')
    op.drop_column('repertoire_nodes', 'gm_my_move_share')
    op.drop_column('repertoire_nodes', 'gm_my_move_score')
    op.drop_column('repertoire_nodes', 'gm_moves')
    op.drop_column('repertoire_nodes', 'gm_total_games')
    # ### end Alembic commands ###
