"""extend exercise for lichess puzzles

Revision ID: cabca61f3d33
Revises: fa79ec43efeb
Create Date: 2026-06-17 17:50:03.855202
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cabca61f3d33'
down_revision: Union[str, None] = 'fa79ec43efeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add source_kind nullable with default, backfill, then enforce NOT NULL.
    op.add_column(
        'exercises',
        sa.Column(
            'source_kind',
            sa.String(length=16),
            nullable=True,
            server_default='blunder',
        ),
    )
    op.execute("UPDATE exercises SET source_kind = 'blunder' WHERE source_kind IS NULL")
    op.alter_column('exercises', 'source_kind', nullable=False, server_default=None)
    op.add_column('exercises', sa.Column('lichess_id', sa.String(length=16), nullable=True))
    op.add_column('exercises', sa.Column('rating_deviation', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('popularity', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('nb_plays', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('opening_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_exercises_difficulty'), 'exercises', ['difficulty'], unique=False)
    op.create_index(op.f('ix_exercises_lichess_id'), 'exercises', ['lichess_id'], unique=True)
    op.create_index(op.f('ix_exercises_source_kind'), 'exercises', ['source_kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_source_kind'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_lichess_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_difficulty'), table_name='exercises')
    op.drop_column('exercises', 'opening_tags')
    op.drop_column('exercises', 'nb_plays')
    op.drop_column('exercises', 'popularity')
    op.drop_column('exercises', 'rating_deviation')
    op.drop_column('exercises', 'lichess_id')
    op.drop_column('exercises', 'source_kind')
    # ### end Alembic commands ###
