"""position session tables

Revision ID: db6787112a13
Revises: caab7def4c9e
Create Date: 2026-06-17 19:32:10.040226
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'db6787112a13'
down_revision: Union[str, None] = 'caab7def4c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('starting_fen', sa.String(length=128), nullable=False),
    sa.Column('current_fen', sa.String(length=128), nullable=False),
    sa.Column('user_color', sa.String(length=8), nullable=False),
    sa.Column('sf_skill_level', sa.Integer(), nullable=False),
    sa.Column('sf_elo', sa.Integer(), nullable=True),
    sa.Column('sf_depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_reason', sa.String(length=64), nullable=True),
    sa.Column('final_ply', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_sessions_player_id'), 'position_sessions', ['player_id'], unique=False)
    op.create_index(op.f('ix_position_sessions_status'), 'position_sessions', ['status'], unique=False)
    op.create_table('position_session_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=False),
    sa.Column('uci', sa.String(length=8), nullable=False),
    sa.Column('san', sa.String(length=10), nullable=False),
    sa.Column('fen_after', sa.String(length=128), nullable=False),
    sa.Column('eval_cp_after', sa.Integer(), nullable=True),
    sa.Column('eval_mate_after', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['position_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pos_sess_moves_session_ply', 'position_session_moves', ['session_id', 'ply'], unique=True)
    op.create_index(op.f('ix_position_session_moves_session_id'), 'position_session_moves', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_session_moves_session_id'), table_name='position_session_moves')
    op.drop_index('ix_pos_sess_moves_session_ply', table_name='position_session_moves')
    op.drop_table('position_session_moves')
    op.drop_index(op.f('ix_position_sessions_status'), table_name='position_sessions')
    op.drop_index(op.f('ix_position_sessions_player_id'), table_name='position_sessions')
    op.drop_table('position_sessions')
    # ### end Alembic commands ###
