"""initial schema

Revision ID: 672e3ae5a9fc
Revises: 
Create Date: 2026-06-17 15:22:13.789520
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '672e3ae5a9fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eco', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('moves_uci', sa.Text(), nullable=False),
    sa.Column('moves_san', sa.Text(), nullable=False),
    sa.Column('fen_signature', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_openings_eco'), 'openings', ['eco'], unique=False)
    op.create_index(op.f('ix_openings_fen_signature'), 'openings', ['fen_signature'], unique=True)
    op.create_index(op.f('ix_openings_name'), 'openings', ['name'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chesscom_username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('is_me', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_chesscom_username'), 'players', ['chesscom_username'], unique=True)
    op.create_index(op.f('ix_players_is_me'), 'players', ['is_me'], unique=False)
    op.create_table('repertoire_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=8), nullable=False),
    sa.Column('fen', sa.String(length=128), nullable=False),
    sa.Column('move_uci', sa.String(length=8), nullable=True),
    sa.Column('move_san', sa.String(length=10), nullable=True),
    sa.Column('is_my_move', sa.Boolean(), nullable=False),
    sa.Column('is_main_line', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('traps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sr_ease', sa.Float(), nullable=False),
    sa.Column('sr_interval_days', sa.Integer(), nullable=False),
    sa.Column('sr_repetitions', sa.Integer(), nullable=False),
    sa.Column('sr_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sr_last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['repertoire_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repertoire_color_fen', 'repertoire_nodes', ['color', 'fen'], unique=False)
    op.create_index(op.f('ix_repertoire_nodes_fen'), 'repertoire_nodes', ['fen'], unique=False)
    op.create_index(op.f('ix_repertoire_nodes_parent_id'), 'repertoire_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_repertoire_nodes_sr_due_at'), 'repertoire_nodes', ['sr_due_at'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('white_player_id', sa.Integer(), nullable=False),
    sa.Column('black_player_id', sa.Integer(), nullable=False),
    sa.Column('white_rating', sa.Integer(), nullable=True),
    sa.Column('black_rating', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('termination', sa.String(length=64), nullable=True),
    sa.Column('time_control', sa.String(length=32), nullable=True),
    sa.Column('time_class', sa.String(length=16), nullable=True),
    sa.Column('rated', sa.Boolean(), nullable=False),
    sa.Column('eco', sa.String(length=8), nullable=True),
    sa.Column('opening_name', sa.String(length=256), nullable=True),
    sa.Column('opening_id', sa.Integer(), nullable=True),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.Column('initial_fen', sa.String(length=128), nullable=True),
    sa.Column('ply_count', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_status', sa.String(length=16), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['black_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['opening_id'], ['openings.id'], ),
    sa.ForeignKeyConstraint(['white_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_analysis_status'), 'games', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_games_eco'), 'games', ['eco'], unique=False)
    op.create_index(op.f('ix_games_external_id'), 'games', ['external_id'], unique=True)
    op.create_index('ix_games_played_at', 'games', ['played_at'], unique=False)
    op.create_table('weaknesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('sample_game_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaknesses_category'), 'weaknesses', ['category'], unique=False)
    op.create_index(op.f('ix_weaknesses_player_id'), 'weaknesses', ['player_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('source_game_id', sa.Integer(), nullable=True),
    sa.Column('source_weakness_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('fen', sa.String(length=128), nullable=False),
    sa.Column('side_to_move', sa.String(length=1), nullable=False),
    sa.Column('solution_uci', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('theme_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('sr_ease', sa.Float(), nullable=False),
    sa.Column('sr_interval_days', sa.Integer(), nullable=False),
    sa.Column('sr_repetitions', sa.Integer(), nullable=False),
    sa.Column('sr_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sr_last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('successes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_game_id'], ['games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_weakness_id'], ['weaknesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_kind'), 'exercises', ['kind'], unique=False)
    op.create_index(op.f('ix_exercises_player_id'), 'exercises', ['player_id'], unique=False)
    op.create_index(op.f('ix_exercises_sr_due_at'), 'exercises', ['sr_due_at'], unique=False)
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('is_white', sa.Boolean(), nullable=False),
    sa.Column('san', sa.String(length=10), nullable=False),
    sa.Column('uci', sa.String(length=8), nullable=False),
    sa.Column('fen_before', sa.String(length=128), nullable=False),
    sa.Column('fen_after', sa.String(length=128), nullable=False),
    sa.Column('clock_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moves_game_id'), 'moves', ['game_id'], unique=False)
    op.create_index('ix_moves_game_ply', 'moves', ['game_id', 'ply'], unique=True)
    op.create_table('move_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('eval_cp', sa.Integer(), nullable=True),
    sa.Column('eval_mate', sa.Integer(), nullable=True),
    sa.Column('eval_cp_before', sa.Integer(), nullable=True),
    sa.Column('eval_mate_before', sa.Integer(), nullable=True),
    sa.Column('cp_loss', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(length=16), nullable=True),
    sa.Column('best_move_uci', sa.String(length=8), nullable=True),
    sa.Column('best_move_san', sa.String(length=10), nullable=True),
    sa.Column('pv', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('multipv', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('move_id')
    )
    op.create_index(op.f('ix_move_analyses_quality'), 'move_analyses', ['quality'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_move_analyses_quality'), table_name='move_analyses')
    op.drop_table('move_analyses')
    op.drop_index('ix_moves_game_ply', table_name='moves')
    op.drop_index(op.f('ix_moves_game_id'), table_name='moves')
    op.drop_table('moves')
    op.drop_index(op.f('ix_exercises_sr_due_at'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_player_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_kind'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_weaknesses_player_id'), table_name='weaknesses')
    op.drop_index(op.f('ix_weaknesses_category'), table_name='weaknesses')
    op.drop_table('weaknesses')
    op.drop_index('ix_games_played_at', table_name='games')
    op.drop_index(op.f('ix_games_external_id'), table_name='games')
    op.drop_index(op.f('ix_games_eco'), table_name='games')
    op.drop_index(op.f('ix_games_analysis_status'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_repertoire_nodes_sr_due_at'), table_name='repertoire_nodes')
    op.drop_index(op.f('ix_repertoire_nodes_parent_id'), table_name='repertoire_nodes')
    op.drop_index(op.f('ix_repertoire_nodes_fen'), table_name='repertoire_nodes')
    op.drop_index('ix_repertoire_color_fen', table_name='repertoire_nodes')
    op.drop_table('repertoire_nodes')
    op.drop_index(op.f('ix_players_is_me'), table_name='players')
    op.drop_index(op.f('ix_players_chesscom_username'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_openings_name'), table_name='openings')
    op.drop_index(op.f('ix_openings_fen_signature'), table_name='openings')
    op.drop_index(op.f('ix_openings_eco'), table_name='openings')
    op.drop_table('openings')
    # ### end Alembic commands ###
