"""exercise source_move_id unique

Revision ID: fa79ec43efeb
Revises: 97956c62ce73
Create Date: 2026-06-17 17:09:43.804378
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fa79ec43efeb'
down_revision: Union[str, None] = '97956c62ce73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('source_move_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_exercises_source_move_id'), 'exercises', ['source_move_id'], unique=True)
    op.create_foreign_key(None, 'exercises', 'moves', ['source_move_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_index(op.f('ix_exercises_source_move_id'), table_name='exercises')
    op.drop_column('exercises', 'source_move_id')
    # ### end Alembic commands ###
